apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app.kubernetes.io/part-of: commerce-catalog
data:
  SPRING_CASSANDRA_CONTACT_POINTS: cassandra
  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  SPRING_ELASTICSEARCH_URIS: http://elasticsearch:9200
  PRODUCT_SERVICE_URL: http://product-service:8081
  SEARCH_SERVICE_URL: http://search-service:8082
  SPRING_PROFILES_ACTIVE: docker
  SERVER_ADDRESS: "0.0.0.0"
  # NodePort for frontend — adjust if you change frontend service port
  CORS_ALLOWED_ORIGINS: http://localhost:30173
