spring.application.name=product-service

spring.cassandra.contact-points=127.0.0.1
spring.cassandra.port=9042
spring.cassandra.keyspace-name=product_catalog
spring.cassandra.local-datacenter=datacenter1
spring.cassandra.schema-action=create_if_not_exists
spring.cassandra.connection.connect-timeout=20s
spring.cassandra.connection.init-query-timeout=20s
spring.cassandra.request.timeout=20s

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

server.port=8081

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always