spring.application.name=product-service

spring.cassandra.contact-points=127.0.0.1
spring.cassandra.port=9042
spring.cassandra.keyspace-name=product_catalog
spring.cassandra.local-datacenter=datacenter1
spring.cassandra.schema-action=create_if_not_exists
spring.cassandra.connection.connect-timeout=20s
spring.cassandra.connection.init-query-timeout=20s
spring.cassandra.request.timeout=20s

server.port=8081