spring.application.name=product-service

spring.cassandra.contact-points=localhost
spring.cassandra.port=9042
spring.cassandra.keyspace-name=product_catalog
spring.cassandra.local-datacenter=datacenter1
spring.cassandra.schema-action=create_if_not_exists

server.port=8081