name: Backend CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  build-and-test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build product-service
        working-directory: product-service
        run: mvn clean test

      - name: Build search-service
        working-directory: search-service
        run: mvn clean test

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build frontend
        working-directory: frontend
        run: |
          npm install
          npm run build